# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.4
      with:
        ssh-private-key: ${{ secrets.PRIVATE_KEY }}
    - name: Copy files to EC2
      run: |
        sudo scp -r -o StrictHostKeyChecking=no ./* ubuntu@${{ secrets.HOST }}:/home/ubuntu/docker_next
    - name: npm 패키지 설치
      run: npm install
    - name: 사용자 Docker 그룹에 추가
      run: |
        sudo usermod -aG docker $USER
    - name: Docker session 로드
      run: |
        sudo chmod 777 /var/run/docker.sock
    - name: Shell 상의 EC2, Docker compose 실행
      run: |
        sudo ssh -r -o StrictHostKeyChecking=no ubuntu@${{ secrets.HOST }} << 'EOF'
          # 여러줄의 명령어를 SSH를 통해 원격으로 EC2 서버에 전송할 수 있도록 함, EOF 로 끝을 알림
          cd /home/ubuntu/docker_next
          docker-compose down
          docker-compose up -d --build
        EOF

        
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
